modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="fastlaunch"
version="b1.9.1"
displayName="TheFastLaunch"
authors="sabu"
description='''
High-performance Minecraft launch accelerator, multi-core asset optimizer, and startup profiler.
'''

[[dependencies.fastlaunch]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.fastlaunch]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="fastlaunch-neoforge.mixins.json"
